### ISSUE TITLE
Suggest service sometimes does not respond

### ISSUE THREAD

**Issue by thadguidry** [wetneb/openrefine-wikidata#6] opened 2017-02-09 03:21 UTC
Hi Antonin,

Spent some time this evening with PR1167 and couldn't get the Suggest service to respond like it did earlier today and provide dropdown suggested Properties for my columns or even the "Reconcile against type:"
However the main guess types was working consistently.
No errors in command console.
FYI

**Comment by wetneb** [comment] 2017-02-09 09:33
Hi Thad,
I can't reproduce this here now, it all works fine here with the new version (after cleaning with Freebase). I'll try to add some server-side logging to monitor how things are going. (And to get some usage stats!)

**Comment by thadguidry** [comment] 2017-02-10 02:14
its not working for me on my desktop...only guess-types-of-column firing off..
Yet things work fine from my work laptop...lol
Anyway for me to see what's going on under the hood in Chrome or Firefox besides dev tools ?

**Comment by thadguidry** [comment] 2017-02-10 02:31
Not working one:
http://127.0.0.1:3333/command/core/guess-types-of-column?project=1754850059635&columnName=Column+2&service=https%3A%2F%2Ftools.wmflabs.org%2Fopenrefine-wikidata%2Fapi

Working one:
http://127.0.0.1:3333/command/core/guess-types-of-column?project=1754850059635&columnName=Column+2&service=https%3A%2F%2Ftools.wmflabs.org%2Fopenrefine-wikidata%2Fen%2Fapi

Ah !  Not working one doesn't have /en/ !

Can you checkout our master now and build and make sure things look good from a clean slate for you and functions well with guess-types-of-column and the property suggest service ?

**Comment by wetneb** [comment] 2017-02-10 11:07
Ah, sorry about that, I will try to reproduce that tonight… I thought I had maintained the previous endpoint (which seems to work, at least when querying it manually).
By the way how to you start OpenRefine from a clean state? I tried moving .share/local/openrefine somewhere else but it looks like some user settings are stored or cached somewhere else?

**Comment by thadguidry** [comment] 2017-02-10 14:44
Use the Dev Build cycle... install Apache Ant 1.9x somewhere and path it.  install JDK 1.7x somewhere and path it.  Checkout the master branch.....cd into it...Then run "./refine clean" and then "./refine build"  then launch "./refine"

Install Instructions has note about Dev Version
https://github.com/OpenRefine/OpenRefine/wiki/Installation-Instructions#development-version

Step by Step link
https://github.com/OpenRefine/OpenRefine/wiki/Get-Development-Version

Don't forget to do SHIFT F5 on your browser after you launch Firefox or  Chrome to clear the cache before you begin trying out the code changes :)

**Comment by jackyq2015** [comment] 2017-02-11 03:55
@wetneb do you have some configuration detail of the server hosting the service? So user can have some idea what level of expectation should have in terms of performance and availability.

**Comment by wetneb** [comment] 2017-02-11 09:56
@jackyq2015 My experience with wmflabs is that you should have very low expectations in terms of availability… (Although it seems more stable now.)

The point of hosting the service there instead of on my own machines is that if I disappear, other wikipedians can take over the project (even the running instance).

If anybody wants to run another instance somewhere else, it should not be hard: all you need is a Redis instance and a web server that support UWSGI (actually you can even forget about the web server and just do "python app.py" but it might be less efficient and secure).

**Comment by wetneb** [comment] 2017-02-11 12:07
I've added some rudimentary monitoring to check the average processing time per query: https://tools.wmflabs.org/openrefine-wikidata/monitoring

**Comment by wetneb** [comment] 2017-07-27 17:05
Closing this issue as Thad's original problem was solved.

**Closed by wetneb** 2017-07-27 17:05 UTC
